import type { Metadata } from "next";
import { Inter } from 'next/font/google'
 
const inter = Inter({ subsets: ['latin'] })
import "./globals.css";
import Header from "@/components/blog-components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased`}
      >
        <Header logo="PROMPT HERO" categories={["ChatGPT", "Midjourney", "Stable Diffusion","DALL-E","GPT-4"]}/>
        {children}
      </body>
    </html>
  );
}
